name: Orcish Archer
id: Orcish Archer
level: 1
cost: 14
health: 32
moves: 5
experience: 30
advances_to: null
image: res://units/images/orcs/archer.png

attacks:
  - {
    name: dagger,
    damage: 4,
    strikes: 2,
    range: melee,
    type: blade,
    icon: res://interface/images/attacks/dagger-orcish.png
  }
  - {
    name: bow,
    damage: 6,
    strikes: 3,
    range: ranged,
    type: pierce,
    icon: res://interface/images/attacks/bow-orcish.png
  }
  - {
    name: bow,
    damage: 7,
    strikes: 2,
    range: ranged,
    type: fire,
    icon: res://interface/images/attacks/bow-orcish.png
  }

resistance:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 100

defense:
  castle: 60
  flat: 40
  forest: 50
  hills: 50
  mountains: 50
  village: 60

movement:
  castle: 1
  flat: 1
  forest: 2
  hills: 1
  mountains: 2
  village: 1