name: Troll Whelp
id: Troll Whelp
level: 1
cost: 13
health: 42
moves: 5
experience: 36
advances_to: Troll
image: res://units/images/trolls/whelp.png

attacks:
  - {
    name: fist,
    damage: 8,
    strikes: 3,
    range: melee,
    type: impact,
    icon: res://interface/images/attacks/fist-troll.png
  }

resistance:
  blade: 80
  pierce: 80
  impact: 100
  fire: 100
  cold: 100
  arcane: 110

defense:
  castle: 40
  flat: 30
  forest: 40
  hills: 50
  mountains: 60
  village: 40

movement:
  castle: 1
  flat: 1
  forest: 2
  hills: 1
  mountains: 2
  village: 1