name: Troll
id: Troll
level: 2
cost: 29
health: 55
moves: 5
experience: 66
advances_to: null
image: res://units/images/trolls/troll.png

abilities:
  - {
    id: regenerate
  }

attacks:
  - {
    name: club,
    damage: 14,
    strikes: 2,
    range: ranged,
    type: impact,
    icon: res://interface/images/attacks/club.png
  }

resistance:
  blade: 80
  pierce: 80
  impact: 100
  fire: 100
  cold: 100
  arcane: 110

defense:
  castle: 40
  flat: 30
  forest: 40
  hills: 50
  mountains: 60
  village: 40

movement:
  castle: 1
  flat: 1
  forest: 2
  hills: 1
  mountains: 2
  village: 1