name: Elvish Archer
id: Elvish Archer
level: 1
health: 29
moves: 6
experience: 44
advances_to: null
image: res://units/images/elves-wood/archer.png

attacks:
  - {
    name: sword,
    damage: 4,
    strikes: 2,
    range: melee,
    type: blade,
    icon: res://interface/images/attacks/sword-elven.png
  }
  - {
    name: bow,
    damage: 5,
    strikes: 4,
    range: ranged,
    type: pierce,
    icon: res://interface/images/attacks/bow-elven.png
  }

resistance:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 110

defense:
  flat: 40
  forest: 70
  hills: 50
  mountains: 60
  village: 60

movement:
  flat: 1
  forest: 1
  hills: 2
  mountains: 3
  village: 1