name: Elvish Scout
id: Elvish Scout
level: 1
health: 32
moves: 9
experience: 32
advances_to: null
image: res://units/images/elves-wood/scout.png

attacks:
  - {
    name: sword,
    damage: 4,
    strikes: 3,
    range: melee,
    type: blade,
    icon: res://interface/images/attacks/sword-elven.png
  }
  - {
    name: bow,
    damage: 6,
    strikes: 2,
    range: ranged,
    type: pierce,
    icon: res://interface/images/attacks/bow-elven.png
  }

resistance:
  blade: 100
  pierce: 120
  impact: 100
  fire: 100
  cold: 100
  arcane: 110

defense:
  flat: 40
  forest: 60
  hills: 50
  mountains: 60
  village: 40

movement:
  flat: 1
  forest: 1
  hills: 2
  mountains: 3
  village: 1