name: Elvish Shaman
id: Elvish Shaman
level: 1
health: 26
moves: 5
experience: 32
advances_to: null
image: res://units/images/elves-wood/shaman.png

attacks:
  - {
    name: staff,
    damage: 3,
    strikes: 2,
    range: melee,
    type: impact,
    icon: res://interface/images/attacks/druidstaff.png
  }
  - {
    name: entangle,
    damage: 3,
    strikes: 2,
    range: ranged,
    type: impact,
    icon: res://interface/images/attacks/entangle.png
  }

resistance:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 110

defense:
  flat: 40
  forest: 60
  hills: 50
  mountains: 60
  village: 60

movement:
  flat: 1
  forest: 1
  hills: 2
  mountains: 3
  village: 1